### ISSUE TITLE
Баг при logon (и не только при logon)

### ISSUE THREAD

**Issue by lastdrv** [inngvar/imanagestuff#56]
Захожу из дома в пятницу в 21:20 (6 мая 2022)
Браузер Firefox 99.0 (64 бита)
Система Linux kubuntu 5.13.0-39-generic Ubuntu SMP Thu Mar 24 15:35:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

На первом же окне получаю An unexpected error has occurred.
TypeError: proj.project is undefined

Хотя project для меня выставлен в one-window
Из офиса днём нормально всё было

Ссылка на скрин https://ibb.co/1721Z0Z

UPD: Винда с хромом тоже самое показывают.

**Comment by lastdrv** [comment]
Теперь из офиса An unexpected error has occurred
В среду 11 мая 2022 16:15

**Comment by inngvar** [comment]
Исправил!
