### ISSUE TITLE
Модальное окно редактирования записи времени не позволяет сохранить новое значение

### ISSUE THREAD

**Issue by ExAnimoso** [inngvar/imanagestuff#83]
Диалог позволяет ввести новое значение, кнопка "сохранить" закрывает диалог. Однако, изменений в таблице с отмеченным временем не происходит (даже после обновления страницы).
Время пробовал вводить в разных форматах с PT и без, кириллицей и латиницей.

**Comment by gladkonik** [comment]
Возможно это тоже что и #81 ?

**Comment by ExAnimoso** [comment]
Похоже на то. Предлагаю закрыть эту или другую задачу как дублирующую.
